### ISSUE TITLE
Are there missing files utils.py

### ISSUE THREAD

**Issue by ZJG0** [gyNancy/phash_public#1]
https://github.com/gyNancy/phash_public/blob/bd087c428a44db2aa49c178c9a769a27018c246e/l2_attack_black.py#L25
I can't find the `utils`, which is a third-party library or your own file?

**Comment by ZJG0** [comment]
https://github.com/gyNancy/phash_public/blob/dd464249b8dd6d6cf42ae7fc1ebb0094d79055ce/test_attack_black.py#L17
Where is `setup_face_hash `?

**Comment by gyNancy** [comment]
Yes sorry there is a missing file utils.py that I just added. You can comment out the setup_face_hash. We only release ImageNet dataset for tutorial purpose. You can ask us for the face dataset if you want.
